# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(GitVersion_NuGetVersion)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.NuGetVersion: ''
steps: 
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: src/BlazUI/BlazUI
    verbose: false
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion 
  inputs: 
    preferBundledVersion: false
 
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/BlazUI.csproj'
 
- task: DotNetCoreCLI@2
  displayName: 'dotnet build' 
  inputs: 
    projects: '**/BlazUI.csproj' 
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)' 
    versioningScheme: byBuildNumber
 
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack' 
  inputs: 
    command: pack
    packagesToPack: '**/BlazUI.csproj' 
    nobuild: true 
    versioningScheme: byEnvVar 
    versionEnvVar: GitVersion.NuGetVersion
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
